--Clsae 19/05
--TEMA: CREACION DE UN DATAWAREHOUSE
--PASOS PARA SU CREACION:
--1.CREACION DE UNA BD DESTINO
--2.CREACION DE LAS DIMENSIONES DE MODELO EN ESTRELLA
--3.INSERCION DE DATOS A LAS DIMENSIONES CREADAS
--4.CREACION DE LA TABLA HECHOS
--5.INSERCION DE LOS DATOS A LA TABLA HECHOS

--PASO 2 CREAR DIMESIONES 

CREATE TABLE DIM_UBICATE(
DUBICATE INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
COUNTRY_ID FLOAT,
COUNTRY_NAME NVARCHAR(255),
CITY_ID FLOAT,
CITY_NAME NVARCHAR(255));

CREATE TABLE DIM_STORE(
DSTORE INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
STORE_ID FLOAT,
STORE_NAME NVARCHAR(255),
STORE_ADRESS NVARCHAR (255),
STORE_PHONE FLOAT,
STORE_EMAIL NVARCHAR (255),
STORE_CITYNAME NVARCHAR (255));

CREATE TABLE DIM_PROVIDER(
DPROVIDER INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
PROVIDER_ID FLOAT,
PROVIDER_NAME NVARCHAR (255),
PROVIDER_RUC FLOAT,
PROVIDER_CONTACT VARCHAR (255),
PROVIDER_ADRESS NVARCHAR (55),
PROVIDER_EMAIL NVARCHAR (55),
PROVIDER_PHONE NVARCHAR (55));

CREATE TABLE DIM_TIME(
DTIME INT IDENTITY (1,1) NOT NULL,
PURCHASE_DATE DATETIME,
ANIO INT,
TRIMESTRE INT,
MES INT,
NOMNRE_MES NVARCHAR (255),
NUMERO_DIA INT,
DIA_SEMANA INT,
NOMBRE_DIA_SEAMANA NVARCHAR (100)
);

CREATE TABLE DIM_PRODUCTOS(
DPRODUCTO INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
PRODUCT_ID FLOAT,
PRODUCT_NAME NVARCHAR(200),
MODEL_YEAR FLOAT,
LIST_PRICE FLOAT,
CATEGORY_NAME NVARCHAR(200),
BRAND_NAME NVARCHAR (200),
STOCK_PRODUCT FLOAT
);

--PASO 3 INSERCION DE LOS DATOS EN UNA DIMENSION USADA 

INSERT INTO DIM_UBICATE --BD DESTINO Y TABL DESTINO
SELECT CO.Country_Id, CO.Country_Name, CT.City_Id, CT.City_Name
FROM BikeStore..City CT   --BD ORIGEN Y TABLA DE ORIGEN "BIKESTORE"
INNER JOIN BikeStore..Country CO ON CT.Country_Id = CO.Country_Id

SELECT * FROM DIM_UBICATE

INSERT INTO DIM_STORE --BD DESTINO Y TABL DESTINO
SELECT ST.Store_Id, ST.Store_Name, ST.Adress, ST.Phone, ST.Email, CI.City_Name
FROM BikeStore..Store ST--BD ORIGEN Y TABLA DE ORIGEN "BIKESTORE"
INNER JOIN BikeStore..City CI ON CI.City_Id = ST.City_Id

SELECT * FROM DIM_STORE 

INSERT INTO DIM_PROVIDER
SELECT Provider_Id, Provider_Name+' '+ Caontact_Last_Name AS Provider_Name, 
PV.ProviderRuc, Cantact_Name, Adress, Mail, Contact_Phone
FROM BIKESTORE..Provider PV

SELECT * FROM DIM_PROVIDER

INSERT INTO DIM_TIME 
SELECT Purchase_Date, YEAR(Purchase_Date) AS ANIO, DATEPART (QUARTER,Purchase_Date) AS TRIMESTRE, MONTH(Purchase_Date) AS MES,
DATENAME(MONTH,Purchase_Date) AS NOMBRE_MES, DAY(Purchase_Date) AS NUMERO_DIA, DATENAME(WEEKDAY,Purchase_Date) AS DIA_SEMANA, 
DBO.NOMBRE_DIA2 (DATENAME (WEEKDAY,Purchase_Date)) AS NOMBRE_DIA_SEMANA --FUNCION QUE YA TENIAMOS
FROM BikeStore..Purchase

SELECT * FROM DIM_TIME

INSERT INTO DIM_PRODUCTOS 
SELECT Purchase_Date, YEAR(Purchase_Date) AS ANIO, DATEPART (QUARTER,Purchase_Date) AS TRIMESTRE, MONTH(Purchase_Date) AS MES,
DATENAME(MONTH,Purchase_Date) AS NOMBRE_MES, DAY(Purchase_Date) AS NUMERO_DIA, DATENAME(WEEKDAY,Purchase_Date) AS DIA_SEMANA, 
DBO.NOMBRE_DIA2 (DATENAME (WEEKDAY,Purchase_Date)) AS NOMBRE_DIA_SEMANA --FUNCION QUE YA TENIAMOS
FROM BikeStore..Purchase

SELECT * FROM DIM_TIME




