--Clsae 19/05
--TEMA: CREACION DE UN DATAWAREHOUSE
--PASOS PARA SU CREACION:
--1.CREACION DE UNA BD DESTINO
--2.CREACION DE LAS DIMENSIONES DE MODELO EN ESTRELLA
--3.INSERCION DE DATOS A LAS DIMENSIONES CREADAS
--4.CREACION DE LA TABLA HECHOS
--5.INSERCION DE LOS DATOS A LA TABLA HECHOS

--0,1 DEPENDENCIAS 

CREATE FUNCTION FUNCION_NOMBRE_DIAS
(@NUMERO_DIA int)
RETURNS VARCHAR (100)
AS
BEGIN
   DECLARE @NOMBRE_DIA VARCHAR (20)
   SET @NOMBRE_DIA = CASE @NUMERO_DIA
     WHEN 1 THEN 'LUNES'
	 WHEN 2 THEN 'MARTES'
	 WHEN 3 THEN 'MIERCOLES'
	 WHEN 4 THEN 'JUEVES'
	 WHEN 5 THEN 'VIERNES'
	 WHEN 6 THEN'SABADO'
	 WHEN 7 THEN'DOMINGO'
	 ELSE 'DIA NO EXISTE'
  END 
  RETURN @NOMBRE_DIA
END
GO

--PASO 1 CREACION DE BD DESTINO 
CREATE DATABASE BD_DESTINO
GO

USE BD_DESTINO
GO 

--PASO 2 CREAR DIMESIONES 

CREATE TABLE DIM_UBICATE(
DUBICATE INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
COUNTRY_ID FLOAT,
COUNTRY_NAME NVARCHAR(255),
CITY_ID FLOAT,
CITY_NAME NVARCHAR(255));

CREATE TABLE DIM_STORE(
DSTORE INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
STORE_ID FLOAT,
STORE_NAME NVARCHAR(255),
STORE_ADRESS NVARCHAR (255),
STORE_PHONE FLOAT,
STORE_EMAIL NVARCHAR (255),
STORE_CITYNAME NVARCHAR (255));

CREATE TABLE DIM_PROVIDER(
DPROVIDER INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
PROVIDER_ID FLOAT,
PROVIDER_NAME NVARCHAR (255),
PROVIDER_RUC FLOAT,
PROVIDER_CONTACT VARCHAR (255),
PROVIDER_ADRESS NVARCHAR (55),
PROVIDER_EMAIL NVARCHAR (55),
PROVIDER_PHONE NVARCHAR (55));

CREATE TABLE DIM_TIME(
DTIME INT IDENTITY (1,1) NOT NULL,
PURCHASE_DATE DATETIME,
ANIO INT,
TRIMESTRE INT,
MES INT,
NOMBRE_MES NVARCHAR (255),
NUMERO_DIA INT,
DIA_SEMANA NVARCHAR (20),
NOMBRE_DIA_SEAMANA NVARCHAR (100)
);

CREATE TABLE DIM_PRODUCTOS(
DPRODUCTO INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
PRODUCT_ID FLOAT,
PRODUCT_NAME NVARCHAR(200),
LIST_PRICE FLOAT,
CATEGORY_NAME NVARCHAR(200),
BRAND_NAME NVARCHAR (200),
BRAND_ID FLOAT,
MODEL_YEAR FLOAT
);

--PASO 3 INSERCION DE LOS DATOS EN UNA DIMENSION USADA 

--INSERCION A TABLA UBICATE  

INSERT INTO DIM_UBICATE --BD DESTINO Y TABL DESTINO
SELECT CO.Country_Id, CO.Country_Name, CT.City_Id, CT.City_Name
FROM BikeStore..City CT   --BD ORIGEN Y TABLA DE ORIGEN "BIKESTORE"
INNER JOIN BikeStore..Country CO ON CT.Country_Id = CO.Country_Id

SELECT * FROM DIM_UBICATE

--INSERCION A TABLA STORE  

INSERT INTO DIM_STORE --BD DESTINO Y TABL DESTINO
SELECT ST.Store_Id, ST.Store_Name, ST.Adress, ST.Phone, ST.Email, CI.City_Name
FROM BikeStore..Store ST--BD ORIGEN Y TABLA DE ORIGEN "BIKESTORE"
INNER JOIN BikeStore..City CI ON CI.City_Id = ST.City_Id

SELECT * FROM DIM_STORE 

--INSERCION A TABLA PROVIDER   CAST(CAST(0x41 AS nvarchar) AS varbinary); (CAST(Caontact_Last_Name AS VARCHAR))

INSERT INTO DIM_PROVIDER
SELECT [Provider_Id
Provider_Id
Provider_Id], Provider_Name+' '+ (CAST(Caontact_Last_Name AS VARCHAR)) AS Provider_Name, 
PV.ProviderRuc, Cantact_Name, Adress, Mail, Contact_Phone
FROM BIKESTORE..[Provider] PV

SELECT * FROM BikeStore..Provider

--INSERCION A TABLA TIME  

INSERT INTO DIM_TIME 
SELECT Purchase_Date, YEAR(Purchase_Date) AS ANIO, DATEPART (QUARTER,Purchase_Date) AS TRIMESTRE, MONTH(Purchase_Date) AS MES,
DATENAME(MONTH,Purchase_Date) AS NOMBRE_MES, DAY(Purchase_Date) AS NUMERO_DIA, DATENAME(WEEKDAY,Purchase_Date) AS DIA_SEMANA, 
(DATENAME (WEEKDAY,Purchase_Date)) AS NOMBRE_DIA_SEMANA --FUNCION QUE YA TENIAMOS
FROM BikeStore..Purchase

SELECT * FROM DIM_TIME

--INSERCION A TABLA PRODUCTOS 
INSERT INTO DIM_PRODUCTOS 
SELECT PR.product_id,PR.product_name, PR.list_price, CA.category_name, BR.[Brand:Name], BR.Brand_id, model_year
FROM BikeStore..[Product] PR 
INNER JOIN BikeStore..Category CA ON  CA.category_id = PR.category_id
INNER JOIN BikeStore..Brand BR ON BR.Brand_Id = PR.brand_id


SELECT * FROM DIM_PRODUCTOS

--PASO 4 CREACION DE LA TABLA HEHOS 


--PASO 5 INSERCION DE LA TABLA HECHOS 





